### ISSUE TITLE
[Bug] Contrast issue on some modals

### ISSUE THREAD

**Issue by sigrunixia** [juanchiparra/obsidian-aurora#1]
Hello! 

There is a contrast issue when viewing themes and plugins. Looks like some text snuck through on the buttons. :)

![CleanShot 2024-10-31 at 20 53 49](https://github.com/user-attachments/assets/5ba56a3b-e9d7-435e-b3aa-fce86f5e0773)

**Comment by juanchiparra** [comment]
Hey, I hadn't noticed, and it's a very visible one. It even looks like a strategy to keep the buttons from being so visible. 

Thanks for reporting it, will be fixed for version 1.0.2
