### ISSUE TITLE
make theme available for older versions of obsidian

### ISSUE THREAD

**Issue by incantatem1** [juanchiparra/obsidian-aurora#3]
i downloaded manually and changed the manifest to be usable for 1.6.7. i don't update often because i don't want my plugins to break. there's no reason why the theme should only be for newer versions of obsidian, it's just css, and it works totally fine for me after i changed the manifest.

**Comment by juanchiparra** [comment]
Hey! Of course, in your case, it makes sense that you don't want to upgrade the version. It was the recommendation I received on Discord. I'll check how much I can downgrade it and for the next version it will be fixed. Thanks for your feedback.

**Comment by incantatem1** [comment]
thank you, i honestly think it would even work with 1.0.0, but i don't know how to check that and i doubt anyone is still using that version...

**Comment by juanchiparra** [comment]
Hey! Sorry for the delay. I just updated the theme and downgraded the minAppVersion, it should work for you now. Thanks!

**Comment by juanchiparra** [comment]
Hey! Sorry for the delay. I just updated the theme and downgraded the minAppVersion, it should work for you now. Thanks!

**Comment by incantatem1** [comment]
it works, awesome, thank you

**Comment by incantatem1** [comment]
could you please make the italic for blockquotes a toggle as well? i find italic really hard to read and often have long texts in blockquotes.
